### ISSUE TITLE
[Feature Request] 通过玩家登录来源创建自动化, 允许自动添加到白名单

### ISSUE THREAD

**Issue by xiaoluofa** [ApliNi/IpacWhitelist#14]
正版和基岩跳过

**Comment by ApliNi** [comment]
假设这是一个功能请求, 让正版账户和基岩版不受白名单影响, 我需要知道你当前使用什么插件支持正版账户和基岩版

**Comment by xiaoluofa** [comment]
mulitlogin，计划给外置加手机验证码了，白名单手动添加也是麻烦

**Comment by xiaoluofa** [comment]
> 假设这是一个功能请求, 让正版账户和基岩版不受白名单影响, 我需要知道你当前使用什么插件支持正版账户和基岩版

我觉得你不需要知道是什么，你判断uuid是不是正版就行了

**Comment by xiaoluofa** [comment]
基岩版uuid前面是0，盗版uuid无法通过正版接口找到对应的name

**Comment by ApliNi** [comment]
> mulitlogin，计划给外置加手机验证码了，白名单手动添加也是麻烦

MultiLogin 插件似乎没有提供任何 API, 我没法通过它判断一个玩家的信息

我准备去检查一下 spigot 有没有提供一些这方面有用的接口, 请等待回复...

---

> 我觉得你不需要知道是什么，你判断uuid是不是正版就行了
> 基岩版uuid前面是0，盗版uuid无法通过正版接口找到对应的name

这样做是不安全且性能差的, 判断 Java 正版账户应该检查玩家是否正确完成了 Minecraft 的正版验证流程, 而判断基岩版目前应该只能通过 Floodgate, 好在 Floodgate 有提供接口

**Comment by ApliNi** [comment]
我将会实现这样一个功能, 以下是预计中的配置
```yaml
  # 根据玩家登录来源自动添加到白名单, 这仅适用于新玩家
  # 请确保启用了对应的 hook 插件配置
  autoWhitelist:
    enable: false
    # 使用 NOT 将取消这项检查, 对于需要网络请求的检查将提高性能
    # 通过 Geyser 插件检查
    onGeyserPlayer: WHITE   # 将所有新的基岩版玩家添加到白名单
    # 通过 mojangApi **粗略**地检查是否为正版账户 https://api.mojang.com/users/profiles/minecraft/<playerName>
    onPremiumPlayer: WHITE  # 将所有新的正版账户添加到白名单
    # 不属于以上任何一类玩家
    onOtherPlayer: NOT      # 不处理其他玩家
```
