### ISSUE TITLE
允许特定 IP 绕过白名单检查

### ISSUE THREAD

**Issue by GuYuan-V** [ApliNi/IpacWhitelist#25]
假人登入也被限制了，能否在配置文件里添加一个设定ip不限制的选项

**Comment by ApliNi** [comment]
不是有 ip 黑名单吗? 你从这个黑名单里移除假人使用的 ip 不就好了

**Comment by GuYuan-V** [comment]
假人不一不可能每个都添加白名单，所以本来就没有白名单，无法移出白名单，能否添加一个使用127.0.0.1地址的都无需白名单的功能，或者自定义一个ip地址

**Comment by ApliNi** [comment]
试一下这个版本: https://github.com/ApliNi/IpacWhitelist/releases/tag/v4.1.3-rc1

**Comment by GuYuan-V** [comment]
可以说一下配置文件写入ip的格式吗，我看看我没有写错，因为测试还是说没有白名单

**Comment by ApliNi** [comment]
修复了一些错误: https://github.com/ApliNi/IpacWhitelist/releases/tag/v4.1.3-rc2

如果你需要允许 (ipv4) `127.0.0.1` 的玩家加入, 那么配置如下:
```yaml
whitelist:
  # 允许这些玩家加入游戏, 不参与白名单检查
  # 与 AutoWL 不同的是, 通过这些方法加入的玩家不会被记入白名单, 也不参与白名单配置中的其他检查
  bypass:
    enable: true
    bypassMaxPlayersLimit: false  # 同时绕过最大玩家数限制
    # 通过 IP 检查玩家
    ipList:
      - '^/127\.0\.0\.1$'
```
